name: WaterWorks Thailand
favicon: null
layout_spectrum: 0.6300171951297671
typography_spectrum: 0.2541599995456636
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#00ffff'
    - '#0000ff'
    - '#5858ff'
    - '#a7a7ff'
  brandStrength: 0.75
  lightness: 0.8319099238142371
  saturation: 0.5625
  rhythmicContrast: 0.1854763189330697
purpose: []
