name: WaterWorks Thailand
favicon: null
layout_spectrum: 0.50826
typography_spectrum: 0.44933
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#00ffff'
    - '#0000ff'
    - '#5858ff'
    - '#a7a7ff'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
